version: '3.9'
services:
    node-app:
        build: .
        environment:
            - PORT=5000
        container_name: node-server
        ports:
            - 5000:5000
        depends_on:
            - mongo
    mongo:
        image: mongo
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: umang
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: FamPay
        volumes:
            - mongo-db:/data/db
        ports:
            - 27017:27017
    mongo-express:
        image: mongo-express
        restart: always
        container_name: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: umang
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
            ME_CONFIG_MONGODB_SERVER: mongo
        depends_on:
            - mongo
volumes:
    mongo-db:
