version: '3.9'
services:
    node-app:
        build: .
        environment:
            - PORT=5000
        ports:
            - 5000:5000
        depends_on:
            - mongo
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: umang
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: FamPay
        volumes:
            - mongo-db:/data/db

volumes:
    mongo-db:
