version: '3.9'
services:
    node-app:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - PORT=5000
            - NODE_ENV=development
            - MONGO_HOST=${MONGO_HOST}
            - MONGO_PORT=${MONGO_PORT}
            - MONGO_DATABASE=${MONGO_DATABASE}
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
        command: npm run dev
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: umang
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: FamPay
